export type LuaApiCompletionType =
  | 'function'
  | 'method'
  | 'property'
  | 'hook'
  | 'constant'
  | 'snippet';

export interface LuaApiCompletion {
  readonly label: string;
  readonly type: LuaApiCompletionType;
  readonly detail: string;
  readonly documentation: string;
  readonly apply?: string;
}

export interface LuaApiGroup {
  readonly id: string;
  readonly label: string;
  readonly completions: readonly LuaApiCompletion[];
}

export const LUA_HOOK_COMPLETIONS: readonly LuaApiCompletion[] = [
  {
    label: 'onSpawn',
    type: 'hook',
    detail: 'function onSpawn(self, ctx)',
    documentation: 'Runs when the object is created.',
    apply: 'function onSpawn(self, ctx)\n  \nend',
  },
  {
    label: 'onTick',
    type: 'hook',
    detail: 'function onTick(self, ctx)',
    documentation: 'Runs on each object update tick.',
    apply: 'function onTick(self, ctx)\n  \nend',
  },
  {
    label: 'onCollision',
    type: 'hook',
    detail: 'function onCollision(self, ctx, other, collision)',
    documentation: 'Runs when this object collides with another object. The collision table includes a kind field.',
    apply: 'function onCollision(self, ctx, other, collision)\n  \nend',
  },
  {
    label: 'onDamage',
    type: 'hook',
    detail: 'function onDamage(self, ctx, amount, source)',
    documentation: 'Runs before this object receives native damage. Return false to cancel or a number to replace the damage amount.',
    apply: 'function onDamage(self, ctx, amount, source)\n  \nend',
  },
  {
    label: 'onDeath',
    type: 'hook',
    detail: 'function onDeath(self, ctx)',
    documentation: 'Runs before this object is removed by death logic.',
    apply: 'function onDeath(self, ctx)\n  \nend',
  },
  {
    label: 'onDespawn',
    type: 'hook',
    detail: 'function onDespawn(self, ctx, reason)',
    documentation: 'Runs before an object script instance is removed and its object-local state is cleared.',
    apply: 'function onDespawn(self, ctx, reason)\n  \nend',
  },
  {
    label: 'onScriptChanged',
    type: 'hook',
    detail: 'function onScriptChanged(self, ctx, oldScriptId, newScriptId)',
    documentation: 'Runs after a live object is rebound from one script to another.',
    apply: 'function onScriptChanged(self, ctx, oldScriptId, newScriptId)\n  \nend',
  },
  {
    label: 'onSpawnedChild',
    type: 'hook',
    detail: 'function onSpawnedChild(self, ctx, child)',
    documentation: 'Runs on the parent after this script spawns or claims a child object.',
    apply: 'function onSpawnedChild(self, ctx, child)\n  \nend',
  },
  {
    label: 'onSpawnedBy',
    type: 'hook',
    detail: 'function onSpawnedBy(self, ctx, parent)',
    documentation: 'Runs on a child object after it is spawned by another scripted object.',
    apply: 'function onSpawnedBy(self, ctx, parent)\n  \nend',
  },
  {
    label: 'onSchedule',
    type: 'hook',
    detail: 'function onSchedule(self, ctx, name)',
    documentation: 'Runs when ctx:after or ctx:every fires.',
    apply: 'function onSchedule(self, ctx, name)\n  \nend',
  },
  {
    label: 'onTimer',
    type: 'hook',
    detail: 'function onTimer(self, ctx, name)',
    documentation: 'Runs when a per-object script timer expires.',
    apply: 'function onTimer(self, ctx, name)\n  \nend',
  },
  {
    label: 'onPlayerNear',
    type: 'hook',
    detail: 'function onPlayerNear(self, ctx, distance)',
    documentation: 'Runs when the player enters the radius configured by ctx:setPlayerNearRadius(radius).',
    apply: 'function onPlayerNear(self, ctx, distance)\n  \nend',
  },
  {
    label: 'onPlayerFar',
    type: 'hook',
    detail: 'function onPlayerFar(self, ctx, distance)',
    documentation: 'Runs when the player leaves the radius configured by ctx:setPlayerNearRadius(radius).',
    apply: 'function onPlayerFar(self, ctx, distance)\n  \nend',
  },
  {
    label: 'onAnimationEnd',
    type: 'hook',
    detail: 'function onAnimationEnd(self, ctx)',
    documentation: 'Runs when the object animation reaches its end.',
    apply: 'function onAnimationEnd(self, ctx)\n  \nend',
  },
  {
    label: 'onOffscreen',
    type: 'hook',
    detail: 'function onOffscreen(self, ctx)',
    documentation: 'Runs when off-screen object handling is reached.',
    apply: 'function onOffscreen(self, ctx)\n  \nend',
  },
  {
    label: 'onPickup',
    type: 'hook',
    detail: 'function onPickup(self, ctx, player)',
    documentation: 'Runs on a bonus or add-on object when the player collects it.',
    apply: 'function onPickup(self, ctx, player)\n  \nend',
  },
  {
    label: 'onLevelStart',
    type: 'hook',
    detail: 'function onLevelStart(ctx)',
    documentation: 'Runs when the current level starts. Level scripts receive ctx only.',
    apply: 'function onLevelStart(ctx)\n  \nend',
  },
  {
    label: 'onLevelTick',
    type: 'hook',
    detail: 'function onLevelTick(ctx, dt)',
    documentation: 'Runs once per gameplay frame for global and selected-level scripts.',
    apply: 'function onLevelTick(ctx, dt)\n  \nend',
  },
  {
    label: 'onLevelComplete',
    type: 'hook',
    detail: 'function onLevelComplete(ctx)',
    documentation: 'Runs once when the player reaches the level finish.',
    apply: 'function onLevelComplete(ctx)\n  \nend',
  },
  {
    label: 'onPlayerRespawn',
    type: 'hook',
    detail: 'function onPlayerRespawn(ctx, player)',
    documentation: 'Runs after the player object is recreated following a death.',
    apply: 'function onPlayerRespawn(ctx, player)\n  \nend',
  },
  {
    label: 'onAddOnAward',
    type: 'hook',
    detail: 'function onAddOnAward(ctx, roll)',
    documentation: 'Runs when an add-on pickup awards a native add-on roll.',
    apply: 'function onAddOnAward(ctx, roll)\n  \nend',
  },
];

export const LUA_SELF_COMPLETIONS: readonly LuaApiCompletion[] = [
  { label: 'x', type: 'method', detail: 'self:x()', documentation: 'Current x position.', apply: 'x()' },
  { label: 'y', type: 'method', detail: 'self:y()', documentation: 'Current y position.', apply: 'y()' },
  {
    label: 'setPosition',
    type: 'method',
    detail: 'self:setPosition(x, y)',
    documentation: 'Moves the object to an absolute position.',
    apply: 'setPosition(x, y)',
  },
  {
    label: 'velocityX',
    type: 'method',
    detail: 'self:velocityX()',
    documentation: 'Current x velocity.',
    apply: 'velocityX()',
  },
  {
    label: 'velocityY',
    type: 'method',
    detail: 'self:velocityY()',
    documentation: 'Current y velocity.',
    apply: 'velocityY()',
  },
  {
    label: 'setVelocity',
    type: 'method',
    detail: 'self:setVelocity(x, y)',
    documentation: 'Sets the object velocity.',
    apply: 'setVelocity(x, y)',
  },
  {
    label: 'addVelocity',
    type: 'method',
    detail: 'self:addVelocity(x, y)',
    documentation: 'Adds to the current object velocity.',
    apply: 'addVelocity(x, y)',
  },
  {
    label: 'direction',
    type: 'method',
    detail: 'self:direction()',
    documentation: 'Current direction in radians.',
    apply: 'direction()',
  },
  {
    label: 'setDirection',
    type: 'method',
    detail: 'self:setDirection(radians)',
    documentation: 'Sets the object direction in radians.',
    apply: 'setDirection(radians)',
  },
  { label: 'frame', type: 'method', detail: 'self:frame()', documentation: 'Current sprite frame.', apply: 'frame()' },
  {
    label: 'setFrame',
    type: 'method',
    detail: 'self:setFrame(frame)',
    documentation: 'Sets the current sprite frame.',
    apply: 'setFrame(frame)',
  },
  {
    label: 'setFrameDuration',
    type: 'method',
    detail: 'self:setFrameDuration(ticks)',
    documentation: 'Sets the current animation frame timer/duration value.',
    apply: 'setFrameDuration(ticks)',
  },
  { label: 'damage', type: 'method', detail: 'self:damage()', documentation: 'Current damage value.', apply: 'damage()' },
  {
    label: 'setDamage',
    type: 'method',
    detail: 'self:setDamage(value)',
    documentation: 'Sets the object damage value.',
    apply: 'setDamage(value)',
  },
  { label: 'typeId', type: 'method', detail: 'self:typeId()', documentation: 'Object type resource ID.', apply: 'typeId()' },
  { label: 'maxDamage', type: 'method', detail: 'self:maxDamage()', documentation: 'Maximum damage for this object type.', apply: 'maxDamage()' },
  { label: 'scoreValue', type: 'method', detail: 'self:scoreValue()', documentation: 'Score value for this object type.', apply: 'scoreValue()' },
  { label: 'mass', type: 'method', detail: 'self:mass()', documentation: 'Object type mass.', apply: 'mass()' },
  { label: 'width', type: 'method', detail: 'self:width()', documentation: 'Object type half-width in game units.', apply: 'width()' },
  { label: 'length', type: 'method', detail: 'self:length()', documentation: 'Object type half-length in game units.', apply: 'length()' },
  { label: 'flags', type: 'method', detail: 'self:flags()', documentation: 'Primary object type flags bitmask.', apply: 'flags()' },
  { label: 'flags2', type: 'method', detail: 'self:flags2()', documentation: 'Secondary object type flags bitmask.', apply: 'flags2()' },
  { label: 'control', type: 'method', detail: 'self:control()', documentation: 'Current object control mode.', apply: 'control()' },
  { label: 'layer', type: 'method', detail: 'self:layer()', documentation: 'Current render/collision layer.', apply: 'layer()' },
  { label: 'setLayer', type: 'method', detail: 'self:setLayer(layer)', documentation: 'Sets the render/collision layer, clamped to valid layers.', apply: 'setLayer(layer)' },
  { label: 'isPlayer', type: 'method', detail: 'self:isPlayer()', documentation: 'Returns true when this object is the player.', apply: 'isPlayer()' },
  { label: 'exists', type: 'method', detail: 'self:exists()', documentation: 'Returns true while this object handle is still valid.', apply: 'exists()' },
  { label: 'isOnScreen', type: 'method', detail: 'self:isOnScreen()', documentation: 'Returns true when this object is near the active camera.', apply: 'isOnScreen()' },
  { label: 'distanceTo', type: 'method', detail: 'self:distanceTo(other)', documentation: 'Distance from this object to another object.', apply: 'distanceTo(other)' },
  { label: 'angleTo', type: 'method', detail: 'self:angleTo(other)', documentation: 'Angle from this object to another object in radians.', apply: 'angleTo(other)' },
  {
    label: 'setInput',
    type: 'method',
    detail: 'self:setInput(throttle, steering)',
    documentation: 'Sets AI-style throttle and steering inputs.',
    apply: 'setInput(throttle, steering)',
  },
  {
    label: 'setControl',
    type: 'method',
    detail: 'self:setControl(mode)',
    documentation: 'Changes the script control mode.',
    apply: 'setControl(mode)',
  },
  { label: 'kill', type: 'method', detail: 'self:kill()', documentation: 'Kills this object.', apply: 'kill()' },
  { label: 'remove', type: 'method', detail: 'self:remove()', documentation: 'Removes this object.', apply: 'remove()' },
  {
    label: 'getState',
    type: 'method',
    detail: 'self:getState(key)',
    documentation: 'Reads an object-local script value for this live object instance.',
    apply: 'getState(key)',
  },
  {
    label: 'setState',
    type: 'method',
    detail: 'self:setState(key, value)',
    documentation: 'Stores an object-local script value for this live object instance. Pass nil to clear the key.',
    apply: 'setState(key, value)',
  },
  {
    label: 'addChild',
    type: 'method',
    detail: 'self:addChild(child)',
    documentation: 'Marks another object as owned by this script instance.',
    apply: 'addChild(child)',
  },
  {
    label: 'removeChild',
    type: 'method',
    detail: 'self:removeChild(child)',
    documentation: 'Removes this script instance as the owner of a child object.',
    apply: 'removeChild(child)',
  },
  {
    label: 'childCount',
    type: 'method',
    detail: 'self:childCount()',
    documentation: 'Counts live objects owned by this script instance.',
    apply: 'childCount()',
  },
];

export const LUA_CTX_COMPLETIONS: readonly LuaApiCompletion[] = [
  {
    label: 'playerDistance',
    type: 'method',
    detail: 'ctx:playerDistance()',
    documentation: 'Distance from this object to the player.',
    apply: 'playerDistance()',
  },
  {
    label: 'levelTime',
    type: 'method',
    detail: 'ctx:levelTime()',
    documentation: 'Current level time in seconds.',
    apply: 'levelTime()',
  },
  {
    label: 'levelNumber',
    type: 'method',
    detail: 'ctx:levelNumber()',
    documentation: 'Current one-based level number.',
    apply: 'levelNumber()',
  },
  {
    label: 'levelResourceId',
    type: 'method',
    detail: 'ctx:levelResourceId()',
    documentation: 'Current level pack resource ID.',
    apply: 'levelResourceId()',
  },
  {
    label: 'levelEndY',
    type: 'method',
    detail: 'ctx:levelEndY()',
    documentation: 'Finish Y coordinate for the current level.',
    apply: 'levelEndY()',
  },
  {
    label: 'player',
    type: 'method',
    detail: 'ctx:player()',
    documentation: 'Returns the player object, or nil.',
    apply: 'player()',
  },
  {
    label: 'playerX',
    type: 'method',
    detail: 'ctx:playerX()',
    documentation: 'Current player x position.',
    apply: 'playerX()',
  },
  {
    label: 'playerY',
    type: 'method',
    detail: 'ctx:playerY()',
    documentation: 'Current player y position.',
    apply: 'playerY()',
  },
  {
    label: 'playerSpeed',
    type: 'method',
    detail: 'ctx:playerSpeed()',
    documentation: 'Current player speed magnitude.',
    apply: 'playerSpeed()',
  },
  {
    label: 'playerDamage',
    type: 'method',
    detail: 'ctx:playerDamage()',
    documentation: 'Current player damage value.',
    apply: 'playerDamage()',
  },
  {
    label: 'teleportPlayer',
    type: 'method',
    detail: 'ctx:teleportPlayer(x, y, direction)',
    documentation: 'Moves the player to an absolute position and recenters the camera. Direction is optional.',
    apply: 'teleportPlayer(x, y, direction)',
  },
  {
    label: 'teleportPlayerRelative',
    type: 'method',
    detail: 'ctx:teleportPlayerRelative(dx, dy, directionOffset)',
    documentation: 'Moves the player by an offset. Direction offset is optional.',
    apply: 'teleportPlayerRelative(dx, dy, directionOffset)',
  },
  {
    label: 'objectTypeExists',
    type: 'method',
    detail: 'ctx:objectTypeExists(typeId)',
    documentation: 'Returns true when the object type resource exists.',
    apply: 'objectTypeExists(typeId)',
  },
  {
    label: 'soundExists',
    type: 'method',
    detail: 'ctx:soundExists(soundId)',
    documentation: 'Returns true when the sound resource exists.',
    apply: 'soundExists(soundId)',
  },
  {
    label: 'frameExists',
    type: 'method',
    detail: 'ctx:frameExists(frameId)',
    documentation: 'Returns true when the sprite frame resource exists.',
    apply: 'frameExists(frameId)',
  },
  {
    label: 'findNearestObject',
    type: 'method',
    detail: 'ctx:findNearestObject(typeId, radius)',
    documentation: 'Returns the nearest matching object within radius, or nil. Use typeId <= 0 for any type.',
    apply: 'findNearestObject(typeId, radius)',
  },
  {
    label: 'countObjects',
    type: 'method',
    detail: 'ctx:countObjects(typeId, radius)',
    documentation: 'Counts matching objects within radius. Use typeId <= 0 for any type.',
    apply: 'countObjects(typeId, radius)',
  },
  {
    label: 'spawnObjectType',
    type: 'method',
    detail: 'ctx:spawnObjectType(typeId, x, y, direction, speed)',
    documentation: 'Spawns an object type at the requested position and returns the spawned object, or nil.',
    apply: 'spawnObjectType(typeId, x, y, direction, speed)',
  },
  {
    label: 'spawnAt',
    type: 'method',
    detail: 'ctx:spawnAt(typeId, x, y, direction, speed)',
    documentation: 'Alias for absolute object spawning. Returns the spawned object, or nil.',
    apply: 'spawnAt(typeId, x, y, direction, speed)',
  },
  {
    label: 'spawnNearPlayer',
    type: 'method',
    detail: 'ctx:spawnNearPlayer(typeId, dx, dy, directionOffset, speed)',
    documentation: 'Spawns an object relative to the player heading. Works from level scripts.',
    apply: 'spawnNearPlayer(typeId, dx, dy, directionOffset, speed)',
  },
  {
    label: 'spawnOnTrack',
    type: 'method',
    detail: 'ctx:spawnOnTrack(typeId, track, y, lateralOffset, speed)',
    documentation: 'Spawns an object at an interpolated point on Track.Up or Track.Down and sets its path-following control.',
    apply: 'spawnOnTrack(typeId, Track.Up, y, lateralOffset, speed)',
  },
  {
    label: 'spawnTrackside',
    type: 'method',
    detail: 'ctx:spawnTrackside(typeId, side, y, offset, control, speed)',
    documentation: 'Spawns an object beside the road edge at a deterministic y/offset. Use RoadSide.Left or RoadSide.Right.',
    apply: 'spawnTrackside(typeId, RoadSide.Left, y, offset, Control.None, speed)',
  },
  {
    label: 'spawnRelative',
    type: 'method',
    detail: 'ctx:spawnRelative(typeId, dx, dy, directionOffset, speed)',
    documentation: 'Spawns an object relative to self and returns the spawned object, or nil.',
    apply: 'spawnRelative(typeId, dx, dy, directionOffset, speed)',
  },
  {
    label: 'despawnChildren',
    type: 'method',
    detail: 'ctx:despawnChildren(limit)',
    documentation: 'Marks child objects owned by this script instance for removal.',
    apply: 'despawnChildren(limit)',
  },
  {
    label: 'playSound',
    type: 'method',
    detail: 'ctx:playSound(soundId)',
    documentation: 'Plays a sound resource.',
    apply: 'playSound(soundId)',
  },
  {
    label: 'addScore',
    type: 'method',
    detail: 'ctx:addScore(points)',
    documentation: 'Adds points to the player score.',
    apply: 'addScore(points)',
  },
  {
    label: 'fireWeapon',
    type: 'method',
    detail: 'ctx:fireWeapon(typeId)',
    documentation: 'Fires an object type as a weapon.',
    apply: 'fireWeapon(typeId)',
  },
  {
    label: 'getScriptState',
    type: 'method',
    detail: 'ctx:getScriptState(key)',
    documentation: 'Reads state shared by all object instances using this script resource.',
    apply: 'getScriptState(key)',
  },
  {
    label: 'setScriptState',
    type: 'method',
    detail: 'ctx:setScriptState(key, value)',
    documentation: 'Stores state shared by all object instances using this script resource.',
    apply: 'setScriptState(key, value)',
  },
  {
    label: 'getLevelState',
    type: 'method',
    detail: 'ctx:getLevelState(key)',
    documentation: 'Reads state scoped to the current level for this script resource.',
    apply: 'getLevelState(key)',
  },
  {
    label: 'setLevelState',
    type: 'method',
    detail: 'ctx:setLevelState(key, value)',
    documentation: 'Stores state scoped to the current level for this script resource.',
    apply: 'setLevelState(key, value)',
  },
  {
    label: 'setTimer',
    type: 'method',
    detail: 'ctx:setTimer(name, seconds)',
    documentation: 'Stores a named timer value.',
    apply: 'setTimer(name, seconds)',
  },
  {
    label: 'getTimer',
    type: 'method',
    detail: 'ctx:getTimer(name)',
    documentation: 'Reads a named timer value.',
    apply: 'getTimer(name)',
  },
  {
    label: 'clearTimer',
    type: 'method',
    detail: 'ctx:clearTimer(name)',
    documentation: 'Clears a named per-object timer.',
    apply: 'clearTimer(name)',
  },
  {
    label: 'timerRemaining',
    type: 'method',
    detail: 'ctx:timerRemaining(name)',
    documentation: 'Returns remaining seconds for a named timer, or nil.',
    apply: 'timerRemaining(name)',
  },
  {
    label: 'after',
    type: 'method',
    detail: 'ctx:after(seconds, name)',
    documentation: 'Schedules a one-shot onSchedule callback for this object.',
    apply: 'after(seconds, name)',
  },
  {
    label: 'every',
    type: 'method',
    detail: 'ctx:every(seconds, name)',
    documentation: 'Schedules a repeating onSchedule callback for this object.',
    apply: 'every(seconds, name)',
  },
  {
    label: 'cancelSchedule',
    type: 'method',
    detail: 'ctx:cancelSchedule(name)',
    documentation: 'Cancels a named timer or schedule for this object.',
    apply: 'cancelSchedule(name)',
  },
  {
    label: 'setPlayerNearRadius',
    type: 'method',
    detail: 'ctx:setPlayerNearRadius(radius)',
    documentation: 'Enables onPlayerNear/onPlayerFar for this object. Use radius <= 0 to disable.',
    apply: 'setPlayerNearRadius(radius)',
  },
];

export const LUA_SNIPPET_COMPLETIONS: readonly LuaApiCompletion[] = [
  {
    label: 'proximityHazard',
    type: 'snippet',
    detail: 'simple proximity-triggered hazard',
    documentation: 'Damages or removes the object when the player is nearby.',
    apply: 'function onTick(self, ctx)\n  if ctx:playerDistance() < 96 then\n    self:kill()\n  end\nend',
  },
  {
    label: 'pickup',
    type: 'snippet',
    detail: 'simple pickup script',
    documentation: 'Adds score and removes the object on collision.',
    apply: 'function onCollision(self, ctx, other)\n  ctx:addScore(100)\n  self:remove()\nend',
  },
  {
    label: 'delayedSpawn',
    type: 'snippet',
    detail: 'timer-triggered spawn',
    documentation: 'Starts a timer on spawn and creates an object when it expires.',
    apply: 'function onSpawn(self, ctx)\n  ctx:setTimer("spawn", 1.0)\nend\n\nfunction onTimer(self, ctx, name)\n  if name == "spawn" then\n    ctx:spawnRelative(typeId, 0, 32, 0, 0)\n  end\nend',
  },
  {
    label: 'proximityTrigger',
    type: 'snippet',
    detail: 'player proximity trigger',
    documentation: 'Runs code when the player enters a configured radius.',
    apply: 'function onSpawn(self, ctx)\n  ctx:setPlayerNearRadius(160)\nend\n\nfunction onPlayerNear(self, ctx, distance)\n  ctx:playSound(soundId)\nend',
  },
];

export const LUA_CONSTANT_COMPLETIONS: readonly LuaApiCompletion[] = [
  { label: 'Control.None', type: 'constant', detail: 'Control.None', documentation: 'No built-in control input.', apply: 'Control.None' },
  { label: 'Control.DriveUp', type: 'constant', detail: 'Control.DriveUp', documentation: 'Built-in drive-up control mode.', apply: 'Control.DriveUp' },
  { label: 'Control.DriveDown', type: 'constant', detail: 'Control.DriveDown', documentation: 'Built-in drive-down control mode.', apply: 'Control.DriveDown' },
  { label: 'Control.CrossRoad', type: 'constant', detail: 'Control.CrossRoad', documentation: 'Built-in cross-road control mode.', apply: 'Control.CrossRoad' },
  { label: 'Control.Cop', type: 'constant', detail: 'Control.Cop', documentation: 'Built-in cop chase control mode.', apply: 'Control.Cop' },
  { label: 'ObjectFlag.Wheel', type: 'constant', detail: 'ObjectFlag.Wheel', documentation: 'Wheel object flag.', apply: 'ObjectFlag.Wheel' },
  { label: 'ObjectFlag.Bounce', type: 'constant', detail: 'ObjectFlag.Bounce', documentation: 'Bounce/collision object flag.', apply: 'ObjectFlag.Bounce' },
  { label: 'ObjectFlag.KillsCars', type: 'constant', detail: 'ObjectFlag.KillsCars', documentation: 'Object kills cars on contact.', apply: 'ObjectFlag.KillsCars' },
  { label: 'ObjectFlag.Damageable', type: 'constant', detail: 'ObjectFlag.Damageable', documentation: 'Object can receive damage.', apply: 'ObjectFlag.Damageable' },
  { label: 'Addon.Lock', type: 'constant', detail: 'Addon.Lock', documentation: 'Lock add-on bit.', apply: 'Addon.Lock' },
  { label: 'Addon.Cop', type: 'constant', detail: 'Addon.Cop', documentation: 'Police jammer add-on bit.', apply: 'Addon.Cop' },
  { label: 'Addon.Turbo', type: 'constant', detail: 'Addon.Turbo', documentation: 'Turbo add-on bit.', apply: 'Addon.Turbo' },
  { label: 'Addon.Spikes', type: 'constant', detail: 'Addon.Spikes', documentation: 'Spikes add-on bit.', apply: 'Addon.Spikes' },
  { label: 'Track.Up', type: 'constant', detail: 'Track.Up', documentation: 'Up-track selector for track spawning.', apply: 'Track.Up' },
  { label: 'Track.Down', type: 'constant', detail: 'Track.Down', documentation: 'Down-track selector for track spawning.', apply: 'Track.Down' },
  { label: 'RoadSide.Left', type: 'constant', detail: 'RoadSide.Left', documentation: 'Left road edge selector for trackside spawning.', apply: 'RoadSide.Left' },
  { label: 'RoadSide.Right', type: 'constant', detail: 'RoadSide.Right', documentation: 'Right road edge selector for trackside spawning.', apply: 'RoadSide.Right' },
];

export const LUA_API_GROUPS: readonly LuaApiGroup[] = [
  { id: 'hooks', label: 'Lifecycle Hooks', completions: LUA_HOOK_COMPLETIONS },
  { id: 'self', label: 'self Methods', completions: LUA_SELF_COMPLETIONS },
  { id: 'ctx', label: 'ctx Methods', completions: LUA_CTX_COMPLETIONS },
  { id: 'constants', label: 'Constants', completions: LUA_CONSTANT_COMPLETIONS },
  { id: 'snippets', label: 'Snippets', completions: LUA_SNIPPET_COMPLETIONS },
];
