/*
 * resources.c - Resource Manager implementation for modern platforms.
 *
 * Reads from resources.dat which contains the game's resource fork data.
 * The format was documented by Nathan Craddock:
 * https://nathancraddock.com/blog/resource-forks-and-lzrw-compression/
 *
 * resources.dat format (from natecraddock/open-reckless-drivin):
 *   Each resource:
 *     [8 bytes]  resource type (4-char code, padded with spaces/nulls)
 *     [4 bytes]  resource ID   (big-endian uint32)
 *     [4 bytes]  resource size (big-endian uint32)
 *     [n bytes]  resource data
 */

#include "mac_compat.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* Path to resources.dat - can be overridden at compile time */
#ifndef RESOURCES_DAT_PATH
#define RESOURCES_DAT_PATH "resources.dat"
#endif

#pragma pack(push, 1)
typedef struct {
    char     resource_type[8]; /* 4-char type code, padded */
    uint32_t id;               /* big-endian */
    uint32_t length;           /* big-endian */
} ResourceHeader;
#pragma pack(pop)

/* The resources.dat file uses native (little-endian) byte order for id/length
 * as generated by natecraddock's Zig tool on x86.
 */
static uint32_t le32(uint32_t v) {
#if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
    /* Swap to host (big-endian) from little-endian */
    return ((v & 0xFF000000u) >> 24) |
           ((v & 0x00FF0000u) >> 8)  |
           ((v & 0x0000FF00u) << 8)  |
           ((v & 0x000000FFu) << 24);
#else
    return v; /* already little-endian on x86/x86_64/ARM LE */
#endif
}

static FILE       *gResourceFile  = NULL;
static long        gResourceStart = 0;

/* SetResLoad flag: when false, suppress "not found" stderr messages */
int g_res_load = 1;

void Pomme_InitResources(void)
{
    if (gResourceFile) return;
    gResourceFile = fopen(RESOURCES_DAT_PATH, "rb");
    if (!gResourceFile) {
        /* Try relative path from executable location */
        fprintf(stderr, "Warning: could not open resources.dat at '%s'\n",
                RESOURCES_DAT_PATH);
    }
}

Handle Pomme_GetResource(ResType theType, short theID)
{
    if (!gResourceFile) {
        Pomme_InitResources();
        if (!gResourceFile) return NULL;
    }

    /* Build 4-char type string from OSType */
    char typeBuf[5];
    typeBuf[0] = (char)((theType >> 24) & 0xFF);
    typeBuf[1] = (char)((theType >> 16) & 0xFF);
    typeBuf[2] = (char)((theType >>  8) & 0xFF);
    typeBuf[3] = (char)((theType      ) & 0xFF);
    typeBuf[4] = 0;

    /* Seek to start of resource data */
    fseek(gResourceFile, gResourceStart, SEEK_SET);

    ResourceHeader hdr;
    while (fread(&hdr, sizeof(hdr), 1, gResourceFile) == 1) {
        uint32_t resID  = le32(hdr.id);
        uint32_t resLen = le32(hdr.length);

        /* Check type match (first 4 bytes of the 8-byte type field) */
        if (memcmp(hdr.resource_type, typeBuf, 4) == 0 &&
            (short)resID == theID)
        {
            /* Found it - allocate and read the data */
            Handle h = NewHandle((Size)resLen);
            if (!h) {
                fprintf(stderr, "Pomme_GetResource: out of memory (size=%u)\n", resLen);
                return NULL;
            }
            if (fread(*h, 1, resLen, gResourceFile) != resLen) {
                fprintf(stderr, "Pomme_GetResource: read error for '%s' id=%d\n",
                        typeBuf, theID);
                DisposeHandle(h);
                return NULL;
            }
            return h;
        }

        /* Skip this resource's data */
        fseek(gResourceFile, (long)resLen, SEEK_CUR);
    }

    if (!g_res_load) return NULL;    /* suppress "not found" warning during probe */
    fprintf(stderr, "Pomme_GetResource: not found: type='%s' id=%d\n",
            typeBuf, theID);
    return NULL;
}

void Pomme_LoadResourceFile(const char *path)
{
    if (gResourceFile) {
        fclose(gResourceFile);
    }
    gResourceFile = fopen(path, "rb");
    gResourceStart = 0;
    if (!gResourceFile) {
        fprintf(stderr, "Pomme_LoadResourceFile: cannot open '%s'\n", path);
    }
}
