import { readFile, writeFile } from 'node:fs/promises';

const root = new URL('..', import.meta.url);
const contract = await readFile(new URL('documentation/reckless.d.lua', root), 'utf8');

function annotationsBefore(start) {
  const precedingLines = contract.slice(0, start).split('\n');
  const lines = [];
  let index = precedingLines.length - 1;
  if ((precedingLines[index] ?? '').trim() === '') index -= 1;
  for (; index >= 0; index -= 1) {
    const line = precedingLines[index]?.trim() ?? '';
    if (!line.startsWith('---@param ') && !line.startsWith('---@return ')) break;
    lines.unshift(line);
  }
  const parameters = lines
    .map((line) => line.match(/^---@param ([A-Za-z_][A-Za-z0-9_]*) (.+)$/))
    .filter((match) => match !== null)
    .map((match) => `${match[1]}: ${match[2]}`);
  const returnMatch = [...lines].reverse().find((line) => line.startsWith('---@return '));
  return {
    parameters,
    returnType: returnMatch?.slice('---@return '.length).trim() ?? null,
  };
}

function documentationFor(receiver, name, annotations) {
  const kind = receiver === 'Object' ? 'Object method' : receiver === 'Context' ? 'Script context method' : 'Lifecycle hook';
  const lines = [`${kind} ${name}.`];
  if (annotations.parameters.length > 0) lines.push(`Parameters: ${annotations.parameters.join(', ')}.`);
  if (annotations.returnType !== null) lines.push(`Returns: ${annotations.returnType}.`);
  return lines.join(' ');
}

function parseMethods(receiver) {
  const methods = [];
  const pattern = new RegExp(`function ${receiver}:([A-Za-z][A-Za-z0-9_]*)\\(([^)]*)\\) end`, 'g');
  for (const match of contract.matchAll(pattern)) {
    const name = match[1];
    const parameters = match[2]?.trim() ?? '';
    const receiverName = receiver === 'Object' ? 'self' : 'ctx';
    const annotations = annotationsBefore(match.index ?? 0);
    methods.push({
      label: name,
      type: 'method',
      detail: `${receiverName}:${name}(${parameters})`,
      documentation: documentationFor(receiver, name, annotations),
      apply: `${name}(${parameters})`,
    });
  }
  return methods;
}

function parseHooks() {
  const hooks = [];
  const pattern = /^function (on[A-Z][A-Za-z0-9_]*)\(([^)]*)\) end$/gm;
  for (const match of contract.matchAll(pattern)) {
    const name = match[1];
    const parameters = match[2]?.trim() ?? '';
    const annotations = annotationsBefore(match.index ?? 0);
    hooks.push({
      label: name,
      type: 'hook',
      detail: `function ${name}(${parameters})`,
      documentation: documentationFor('Hook', name, annotations),
      apply: `function ${name}(${parameters})\n  \nend`,
    });
  }
  return hooks;
}

function parseConstants() {
  const constants = [];
  const pattern = /---@class (Control|ObjectFlag|Addon|Track|RoadSide)[\s\S]*?\n(?:---@field [^\n]+\n)*[A-Za-z]+ = \{/g;
  for (const match of contract.matchAll(pattern)) {
    const group = match[1];
    for (const field of match[0].matchAll(/---@field ([A-Za-z][A-Za-z0-9_]*)/g)) {
      const label = `${group}.${field[1]}`;
      constants.push({
        label,
        type: 'constant',
        detail: label,
        documentation: `${label} constant.`,
        apply: label,
      });
    }
  }
  return constants;
}

function quote(value) {
  return JSON.stringify(value);
}

function render(name, values) {
  const lines = [`export const ${name}: readonly LuaApiCompletion[] = [`];
  for (const value of values) {
    lines.push('  {');
    lines.push(`    label: ${quote(value.label)},`);
    lines.push(`    type: ${quote(value.type)},`);
    lines.push(`    detail: ${quote(value.detail)},`);
    lines.push(`    documentation: ${quote(value.documentation)},`);
    lines.push(`    apply: ${quote(value.apply)},`);
    lines.push('  },');
  }
  lines.push('];', '');
  return lines.join('\n');
}

const generated = [
  '// Generated by scripts/generate-lua-api.mjs. Do not edit manually.',
  "import type { LuaApiCompletion } from './lua-script-api.types';",
  '',
  render('LUA_SELF_COMPLETIONS', parseMethods('Object')),
  render('LUA_CTX_COMPLETIONS', parseMethods('Context')),
  render('LUA_HOOK_COMPLETIONS', parseHooks()),
  render('LUA_CONSTANT_COMPLETIONS', parseConstants()),
  `export const LUA_LUA_LS_CONTRACT = ${quote(contract)};`,
].join('\n');

await writeFile(new URL('angular-site/src/app/lua-script-api.generated.ts', root), generated);
